name: Build DirectX 11 Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Étape 1 : Récupère le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Génère le fichier Visual Studio avec un script PowerShell
    - name: Generate Visual Studio project
      run: |
        $xmlContent = @"
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Release|x64">
      <Configuration>Release</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <ProjectGuid>{12345678-ABCD-1234-ABCD-1234567890AB}</ProjectGuid>
    <Keyword>Win32Proj</Keyword>
    <RootNamespace>XIS</RootNamespace>
    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseDebugLibraries>false</UseDebugLibraries>
    <PlatformToolset>v143</PlatformToolset>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ItemGroup>
    <ClCompile Include="XIS_DirectX11_Base.cpp" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
</Project>
"@
        Set-Content -Path XIS.vcxproj -Value $xmlContent

    # Étape 3 : Installe MSBuild
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    # Étape 4 : Compile le projet
    - name: Build the Project
      run: msbuild /p:Configuration=Release /p:Platform=x64 XIS.vcxproj

    # Étape 5 : Publie les artefacts (facultatif)
    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: XIS-Build
        path: |
          **/Release/XIS.exe
